### ISSUE TITLE
Add  support for NetStandard2.0 ?

### ISSUE THREAD

**Issue by snakefoot** [corentinaltepe/nlog.loki#15]
Could this line:

https://github.com/corentinaltepe/nlog.loki/blob/750a0f0cae6ec835c33ec25cd73dd1a3a4293aad/src/NLog.Loki/NLog.Loki.csproj#L4

Be changed to this line (Notice `TargetFrameworks`):
```xml
        <TargetFrameworks>net6.0;netstandard2.0</TargetFrameworks> 
```

Together with this nuget-reference:
```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Net.Http.Json" Version="5.0.0" />
</ItemGroup>
```
Thus making the nuget-package accessible for more users.

**Comment by corentinaltepe** [comment]
Hello. Thank you very much for your suggestion. Yes we should add a target to `netstandard2.0`.

It might not be that simple though. I believe I may have used some .NET 6 features in [the json serializer](https://github.com/corentinaltepe/nlog.loki/blob/master/src/NLog.Loki/LokiEventSerializer.cs). Not sure, I'll have to try and see. Ideally, I'd like to keep the .NET 6 specific code if it shows better performance, so that there's no trade-off to adding a target to `netstandard2.0` for .NET 6 users.

**Comment by snakefoot** [comment]
Thank you very much. The new [nuget-package](https://www.nuget.org/packages/NLog.Targets.Loki) looks great.
