### ISSUE TITLE
The log does not contain the include parameters

### ISSUE THREAD

**Issue by drbogar** [corentinaltepe/nlog.loki#42]
Hi!

I want to use this NLog Loki target with [my Logfmt Layout], but I can't figure out why the properties and context variables don't appear in the result.
It seems as if the layout does not get these variables. I tried it and it works with console target. What am I doing wrong?

This is my Loki target config:
```
NLog.Loki.LokiTarget lokiTarget = new NLog.Loki.LokiTarget()
{
    BatchSize = 200,
    TaskDelayMilliseconds = 500,
    Endpoint = "http://log.example.com",
    Username = "promtail",
    Password = "SuperSecretPassword",
    OrderWrites = false,
    CompressionLevel = System.IO.Compression.CompressionLevel.NoCompression,
    IncludeCallSite = true,
    IncludeCallSiteStackTrace = true,
    IncludeEventProperties = true,
    IncludeGdc = true,
    IncludeScopeNested = true,
    IncludeScopeProperties = true,
    RetryCount = 5,
    RetryDelayMilliseconds = 500,
    Layout = new NLog.Layouts.LogfmtLayout.LogfmtLayout(),
    Labels = 
    {
        new LokiTargetLabel()
        {
            Name = "host",
            Layout = host
        },
        new LokiTargetLabel()
        {
            Name = "app",
            Layout = assemblyName
        }
    }
};
```

[my Logfmt Layout]: https://github.com/drbogar/NLog.LogfmtLayout

**Comment by corentinaltepe** [comment]
Hello @drbogar.

1. Can you work the problem backwards in an attempt to isolate the root cause?
  - replace `host` and `assemblyName` with hardcoded strings, like `"A"`, and `"B"`
  - replace the `new NLog.Layouts.LogfmtLayout.LogfmtLayout()` with a hardcoded string like `"${level}|${message}"`
 
Do you have the logs working again at some point? If not, then it's a Loki deployment/configuration issue. If they do work, then I'd ask about how the LogfmtLayout renders. Is it possible output its string representation?

2. Enable NLog internal logs at a low level and see if there are inconsistent outputs that could indicate layout issues.

**Comment by corentinaltepe** [comment]
I've checked the source code. The target does render the log line using its Layout for every log line. So I'm not sure what's missing.

https://github.com/corentinaltepe/nlog.loki/blob/808914c9883fc95bb855544c742c1cd7fde8d5e9/src/NLog.Loki/LokiTarget.cs#L78

**Comment by corentinaltepe** [comment]
Wow, thank you @snakefoot!

@drbogar, can you try again without `[ThreadAgnostic]` and let us know if that solves your issue?

**Comment by drbogar** [comment]
Thank you @snakefoot ! This solved the problem.

But I don't understand why they appear for the console target.

**Comment by snakefoot** [comment]
The Console-Target is synchronous by default where application-thread is writing, which makes `[ThreadAgnostic]` "work" because context-capture is not needed.

If you wrapped the Console-Target using [AsyncTargetWrapper](https://nlog-project.org/documentation/v5.0.0/html/T_NLog_Targets_Wrappers_AsyncTargetWrapper.htm), then the Layout would also fail (The async background thread cannot render the output, because context-capture has been skipped)
