### ISSUE TITLE
Logs not making it to Loki

### ISSUE THREAD

**Issue by davidlfox** [corentinaltepe/nlog.loki#68]
just working up a proof of concept.
[.net 7 console application repo](https://github.com/davidlfox/lokitest)

installed grafana/loki/promtail using the docker setup. endpoints like /metrics and /ready work from localhost and from another box. ip address in nlog.config is good. no auth, so i omitted username and password.

curl from localhost works to post events to loki
`curl -v -H "Content-Type: application/json" -XPOST -s "http://localhost:3100/loki/api/v1/push" --data-raw   '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "1675029208000000000", "fizzbuzz" ] ] }]}'`
curl from another box (where app is running) works to post events to loki
`curl -v -H "Content-Type: application/json" -XPOST -s "http://my.good.ip.address:3100/loki/api/v1/push" --data-raw   '{"streams": [{ "stream": { "foo": "bar2" }, "values": [ [ "1675029208000000000", "fizzbuzz" ] ] }]}'`
app itself **doesn't post events to loki**

i confirmed the curl statements above worked by using the `logcli` tool on the box. also grafana seems to see them ok. but no luck with the events from my app.

im tossing some random events at it. my label/value's may not make sense.

my goal is to use nlog.loki in a handful of different console applications for different tenants to log a handful of different types of events and then visualize with grafana.

**Comment by corentinaltepe** [comment]
Hi @davidlfox.

Sorry to hear you don't get the logs working in your app. I don't have a definitive idea about what could cause the issue.

Just out of the blue, since the logger batches and pushes messages asynchronously, it could be that the app is closed before the logs could be pushed asynchronously. Could you force an async delay before the end of the app ?
```cs
await Task.Delay(10000);
```

Also, try to force flush the logger before closing the app with https://nlog-project.org/documentation/v4.0.0/html/M_NLog_LogManager_Flush.htm.

Alternatively, force an infinite loop like [this sample](https://github.com/corentinaltepe/nlog.loki/blob/master/src/Template/Program.cs).

Let me know if that works for you!

**Comment by corentinaltepe** [comment]
I'm glad your issue was resolved. I'm not sure what the exact implementation is for a shutdown that was not sufficient with a flush. It is implemented by NLog though, not by the loki target for NLog.
See: https://github.com/NLog/NLog/wiki/Tutorial#5-remember-to-flush
